name: kwartracker
description: Wallet Application
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.3.0
  cloud_firestore_web: ^2.2.0
  cupertino_icons: ^1.0.3
  file_picker: ^3.0.3
  firebase_auth: ^2.0.0
  firebase_auth_web: ^2.0.0
  firebase_core: ^1.3.0
  firebase_core_web: ^1.1.0
  firebase_storage: ^9.0.0
  firebase_storage_web: ^2.0.0
  flutter:
    sdk: flutter
  flutter_iconpicker: ^3.0.2
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  google_sign_in: ^5.0.0
  horizontal_card_pager: ^1.1.1
  intl: ^0.17.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/cards/
    - images/icons/
    - images/users/
