name: kwartracker
description: Wallet Application
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  intl: ^0.17.0
  provider: ^5.0.0
  flutter_svg: ^0.22.0
  horizontal_card_pager: ^1.1.1
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  firebase_storage: ^9.0.0
  firebase_core_web: ^1.1.0
  firebase_auth_web: ^2.0.0
  cloud_firestore_web: ^2.2.0
  firebase_storage_web: ^2.0.0
  modal_progress_hud: ^0.1.3
  fluttertoast: ^8.0.7
  carousel_slider: ^4.0.0
  flutter_iconpicker: ^3.0.2
  file_picker: ^3.0.3
  tree_view: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/cards/
    - images/icons/
    - images/users/
